[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
monitor_filters = esp32_exception_decoder, time, send_on_enter
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
lib_deps = 
    sparkfun/SparkFun BNO080 Cortex Based IMU @ ^1.1.12
    https://github.com/micro-ROS/micro_ros_platformio

board_microros_distro = jazzy
board_microros_transport = serial

build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -std=gnu++17
    -Wall
    -Wformat=2
build_unflags = 
    -std=gnu++11

board_build.partitions = default.csv

[env:ci]
extends = env:esp32dev
build_flags = 
    ${env:esp32dev.build_flags}
    -DUSE_MICROROS=0
lib_deps = 
    sparkfun/SparkFun BNO080 Cortex Based IMU @ ^1.1.12